# Generated by Django 4.1.5 on 2023-01-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="tags",
            field=models.ManyToManyField(blank=True, to="core.tag"),
        ),
    ]
